repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: 'v4.1.0'
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/hakancelik96/unimport
    rev: 0.9.4
    hooks:
      - id: unimport
        args: [--remove, --requirements, --include-star-import]
  - repo: https://github.com/psf/black
    rev: '22.1.0'
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
      - id: flake8
  - repo: https://github.com/kynan/nbstripout
    rev: 0.5.0
    hooks:
      - id: nbstripout
        files: '.ipynb'
