name: Build

on: [pull_request, push]
  #pull_request:
  #push:
  #schedule:
  #    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  Lint and test check:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.10]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    #- name: Install dependencies
    #  run:
    #    python -m pip install --upgrade pip
    #    pip install tox tox-gh-actions
    #    make install
    #- name: Test with tox
    #  run: tox -e py
    - name: Bandit Check
      uses: jpetrucciani/bandit-check@1.6.2
      
    - name: Install flake8
      run: pip install flake8

    - name: Flake8 Check
      uses: suo/flake8-github-action@v1
      with:
        checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
